### ISSUE TITLE
[Invalid] Lyrics Getter Connection Status False

### ISSUE THREAD

**Issue by Brolomna** [YouCanAi/LyricsGetterExt#7] opened 2023-11-08 03:29 UTC
I have given the notification permission also. But the Lyrics Getter Connection Status is False.

**Comment by Brolomna** [comment] 2023-11-08 03:29
![Uploading Screenshot_2023-11-08-09-14-13-362_cn.lyric.getter.jpg…]()

**Comment by YouCanAi** [comment] 2023-11-08 09:42
What‘s your image? I can't see than...

**Comment by YouCanAi** [comment] 2023-11-08 09:46
I thought it was my internet, but I'm having trouble finding your image link in Chrome's DevTools, which makes it impossible for me to determine the cause of the problem.

**Comment by YouCanAi** [comment] 2023-11-08 14:39
It's been a while and still no reply from you, I have a couple of options on my end to address that issue.

First of all, please check your Lyrics Getter rule list to see if the current supported API version of Lyrics Getter matches the API of Lyrics Getter Ext, if not, please try to upgrade Lyrics Getter and Lyrics Getter Ext to the latest version.
([As of now](https://github.com/xiaowine/Lyric-Getter/releases/tag/13-2.0.5), the latest API version on [Lyrics Getter's releases page](https://github.com/xiaowine/Lyric-Getter/releases) is still not 7, so please go to [Lyrics Getter's Action page](https://github.com/xiaowine/Lyric-Getter/actions/workflows/android.yml) to download the [available CI version](https://github.com/xiaowine/Lyric-Getter/actions/runs/6782135062))

Secondly, please check if Lyrics Getter Ext is successfully Hooked on by Lyrics Getter in Xposed Manager. If it is already enabled in the manager, please try to re-enable it to make sure it is enabled properly.
[tutorials](https://github.com/YouCanAi/LyricsGetterExt#whats-this-)

**Comment by YouCanAi** [comment] 2023-11-08 14:42
Please note that granting notification permission does not mean that Lyrics Getter Connection Status will become true, if your device system is Flyme, you can disregard the Lyrics Getter Connection Status, and use Lyrics Getter Ext in Flyme without Lyrics Getter.

**Comment by YouCanAi** [comment] 2023-11-12 07:11
The current issue has been unanswered for 4 days, if after 7 days there is still no reply from the questioner or anyone else I will close this issue.

**Closed as not planned** 2023-11-14 12:39 UTC
Labels: invalid
